services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # Interfaccia web di Neo4j
      - "7687:7687"  # Bolt (protocollo di comunicazione)
    environment:
      NEO4J_AUTH: "neo4j/password"  # Username e password
    volumes:
      - neo4j-data:/data  # Volume anonimo per i dati
      - ./neo4j/logs:/logs  # Mantieni i log sulla macchina host
      - ./neo4j/import:/var/lib/neo4j/import  # Mappatura locale per import
      - ./neo4j/plugins:/plugins  # Mappatura locale per plugin
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Porta per accedere a MongoDB
    volumes:
      - mongo-data:/data/db  # Volume anonimo per i dati
      - ./mongo/logs:/var/log/mongodb  # Mantieni i log sulla macchina host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  python-app:
    build: ./python
    container_name: python-app
    depends_on:
      - neo4j
      - mongo
    volumes:
      - ./python:/usr/src/app
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "test"
      MONGO_URI: "mongodb://root:example@mongo:27017/"

# Definizione dei volumi anonimi
volumes:
  neo4j-data:
  mongo-data:
